config/routes.rb
Rails.application.routes.draw do
  get '/search', to: 'search#index', as: 'search'
  resources :authorships
  resources :authors
  resources :categories
  root to: 'search#index'

  resources :articles do
    collection { get :search }
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/article.rb
class Article < ApplicationRecord
  has_and_belongs_to_many :categories, after_add:    [ lambda { |a,c| Indexer.perform_async(:update,  a.class.to_s, a.id) } ],
                                       after_remove: [ lambda { |a,c| Indexer.perform_async(:update,  a.class.to_s, a.id) } ]
  has_many                :authorships
  has_many                :authors, through: :authorships
  has_many                :comments

  include Searchable
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: %i[show edit update destroy]

  def index
    @articles = Article.page(params[:page])
  end

  def search
    @articles = Article.search(params[:q]).page(params[:page]).records

    render action: 'index'
  end

  def show; end

  def new
    @article = Article.new
  end

  def edit; end

  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_article
    @article = Article.find(params[:id])
  end

  def article_params
    params.require(:article).permit(:title, :content, :published_on)
  end
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/views/articles/_form.html.erb
<%= form_with(model: article, local: true) do |form| %>
  <% if article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
        <% article.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="form-group">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <div class="form-group">
    <%= form.label :published_on %>
    <%= form.date_select :published_on %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing Article</h1>

<%= render 'form', article: @article %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<p id='notice'><%= notice %></p>

<h1><%= controller.action_name == 'search' ? 'Search results' : 'Articles' %></h1>

<hr>
  <%= form_tag search_articles_path, method: 'get' do %>
    <div class='input-group'>
      <%= text_field_tag :q, params[:q], class: 'form-control', placeholder: 'Search...' %>
    </div>
  <% end %>
<hr>

<table class='table table-hover'>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th>Published on</th>
      <th colspan='3'></th>
    </tr>
  </thead>
  <tbody>
    <% @articles.__send__ controller.action_name == 'search' ? :each_with_hit : :each do |article, hit| %>
      <tr>
        <td><%= hit.try(:highlight).try(:title)   ? hit.highlight.title.join.html_safe : article.title %></td>
        <td><%= hit.try(:highlight).try(:content) ? hit.highlight.content.join('&hellip;').html_safe : article.content %></td>
        <td><%= article.published_on %></td>
        <td style='width: 50px'><%= link_to 'Show', article , class: 'btn btn-outline-primary btn-sm'%></td>
        <td style='width: 50px'><%= link_to 'Edit', edit_article_path(article) , class: 'btn btn-outline-primary btn-sm'%></td>
        <td style='width: 50px'><%= link_to 'Destroy', article, method: :delete, data: { confirm: 'Are you sure?' } , class: 'btn btn-outline-primary btn-sm'%></td>
      </tr>
    <% end %>
  </tbody>
</table>

<div class='text-center'>
  <%= paginate @articles %>
</div>

<hr>
<p style="text-align: center; margin-bottom: 21px">
  <%= link_to 'New Article', new_article_path, class: 'btn btn-primary btn-xs', style: 'color: #fff' %>
  <%= link_to 'All Articles', articles_path, class: 'btn btn-primary btn-xs', style: 'color: #fff' if params[:q] %>
</p>

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render 'form', article: @article %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @article.content %>
</p>

<p>
  <strong>Published on:</strong>
  <%= @article.published_on %>
</p>

<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Back', articles_path %>